# actions to upload sdk on s3 after main push
name: Add a file to a bucket
on:
  push:
    branches:
      - 'main'

jobs:
  upload-sdk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Upload file to bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          VERSION: ${{ steps.package-version.outputs.current-version}}
          FILE: ./lib/gladiaio-sdk.js
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: aws s3 cp $FILE $S3_BUCKET/gladia/sdk/$VERSION/gladiaio-sdk.js
