name: continuous integration delivery
on: 
  pull_request:

jobs:

  generate-sdk:
    name: Generate SDK
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code of the application
        uses: actions/checkout@v1
        with:
          persist-credentials: false

      - name: install node ${{ matrix.node-version }} on the container
        uses: actions/setup-node@v1
        with:
          node-version: 18.4.0

      - name: install npm dependencies
        run: npm ci

      - name: generate metadata
        run: npm run generate-metadata

      - name: generate sdk
        run: npm run generate-sdk

      - name: lint
        run: npm run lint

      - name: tests
        run: npm run test

      - name: build the application
        run: npm run build
